stages:
  - build-and-analyse

variables:
  JT: bin/jt
  GIT_SUBMODULE_STRATEGY: normal
  WORKING_BRANCH: clean-repo

.scripts:
   prep-path: &PREP_PATH |
     export PROJECT_FOLDER=$(pwd)
     export PATH=${PROJECT_FOLDER}/bin:${PATH}

analysis_job:
  stage: build-and-analyse
  tags: [yuria2]
  allow_failure: true
  script:
    - *PREP_PATH

    - bash run-several.sh