stages:
  - build-and-analyse

variables:
  JT: bin/jt
  GIT_SUBMODULE_STRATEGY: normal
  WORKING_BRANCH: clean-repo
  GRAAL_BRANCH: dls/test-fail
  TR_BRANCH: update-truby
  ANALYZER_BRANCH: switch-to-data-table
  SRC_GRAAL: graal
  SRC_TR: truffleruby
  SRC_MX: mx
  SRC_ANALYZER: behaviour-analysis


.scripts:
  prep-path: &PREP_PATH |
     export PROJECT_FOLDER=$(pwd)
     export PATH=${PROJECT_FOLDER}/bin:${PATH}
  
  fetch_deps: &FETCH_DEPS |
    export PROJECT_FOLDER=$(pwd)
    cd ${PROJECT_FOLDER}/${SRC_GRAAL}
    git -C ${PROJECT_FOLDER}/${SRC_GRAAL} fetch --all || true

    git -C ${PROJECT_FOLDER}/${SRC_MX} fetch || true

    cd ${PROJECT_FOLDER}/${SRC_TR}
    git -C ${PROJECT_FOLDER}/${SRC_TR} fetch --all || true

    cd ${PROJECT_FOLDER}/${SRC_ANALYZER}
    git -C ${PROJECT_FOLDER}/${SRC_ANALYZER} fetch --all || true
    cd ..


  build_tr: &BUILD_TR |
    echo $(pwd)
    export GIT_DIR=${PROJECT_FOLDER}/${SRC_TR}/.git

    cd ./${SRC_TR}
    git fetch --all || true
    git checkout ${TR_BRANCH}
    ${JT} build --sforceimports --env jvm-ce
    cd ../${SRC_TR}
    ${JT} --use jvm-ce ruby -S gem install bindata

    cd ../${SRC_ANALYZER}/splitting-transition/src ; javac *.java
    cd ..

analysis_job:
  stage: build-and-analyse
  tags: [yuria2]
  allow_failure: true
  script:
    - *PREP_PATH
    - *FETCH_DEPS
    - *BUILD_TR

    - bash run-several.sh